Solved tasks added
Alex27Khalupka/Go-Course pull request #1
Opened 2020-04-13 19:03 UTC by Alex27Khalupka

Task1.go - finding median number for array of integers.
Task2.go - task with square.

2020-04-14 14:15 UTC, ikamornikau requested changes
Please address the requested changes.

2020-04-14 14:15 UTC, ikamornikau commented on FirstHomework/Task1.go
> +	} else {
Do we need `else` here? If the condition above isn't met, the flow will pass by the section.
I would prefer:
```
if len(i) % 2 == 1 {
        return float64(i[len(i) / 2])
}

return ...
```

2020-04-14 14:15 UTC, ikamornikau commented on FirstHomework/Task2.go
> +type Point struct {
Please provide a comment to describe the type.

2020-04-14 14:15 UTC, ikamornikau commented on FirstHomework/Task2.go
> +type Square struct {
Please add a comment to describe the type.

2020-04-14 14:15 UTC, ikamornikau commented on FirstHomework/Task2.go
> +	a uint
What is `a`? Could you please add a comment to provide more clarity?

2020-04-14 14:15 UTC, ikamornikau commented on FirstHomework/Task2.go
> +func (s Square) End () Point {
What is `End()`? What does it do? Please add more clarity by adding a comment.

2020-04-14 14:15 UTC, ikamornikau commented on FirstHomework/Task1.go
> +	array := []int{9, 7, 2, 5, 3, 6}
Please add one more case for odd amount of elements.

2020-04-14 14:16 UTC, ikamornikau commented
Please `go fmt` your code.

2020-04-14 15:00 UTC, ikamornikau approved these changes

2020-04-17 10:11 UTC, wshaman commented on FirstHomework/Task1.go
> +	EvenArray := []int{9, 7, 2, 5, 3, 6}
Is this array or slice?

2020-04-17 10:22 UTC, Alex27Khalupka commented on FirstHomework/Task1.go
> +	EvenArray := []int{9, 7, 2, 5, 3, 6}
Slice

2020-04-17 11:04 UTC, wshaman approved these changes

2020-04-21 12:33 UTC, merged