Homework2 added
Alex27Khalupka/Go-Course pull request #2
Opened 2020-04-17 13:03 UTC by Alex27Khalupka

2020-04-20 13:28 UTC, ikamornikau requested changes
Please address the requested changes.

2020-04-20 13:28 UTC, ikamornikau commented on Homework2/Task1.go
> +// Returns average value of the array
A comment should start with a `type/method` name. Imagine you write a several-lines comment where you describe several actions - without `type/method` name it can be difficult to understand.

2020-04-20 13:28 UTC, ikamornikau commented on Homework2/Task2.go
> +// Returns the longest word from the slice of strings
The same remark about comments here.

2020-04-20 13:28 UTC, ikamornikau commented on Homework2/Task3.go
> +// Returns the copy of the original slice in reverse order.
The same remark about comments here.

2020-04-20 13:28 UTC, ikamornikau commented on Homework2/Task3.go
> +		reversedSlice[opp] = slice[i]
You don't really need this (`reversedSlice[opp] = slice[i]`) operation. Try to run your code without it and you'll get the same result.

2020-04-20 13:28 UTC, ikamornikau commented on Homework2/Task4.go
> +// Prints map values sorted in order of increasing keys.
The same remark about comments here.

2020-04-20 20:24 UTC, wshaman approved these changes
Overall seems good. Just keep in mind notes from @ikamornikau

2020-04-21 11:21 UTC, VolhaVetrava approved these changes

2020-04-24 12:52 UTC, merged